### ISSUE TITLE
protected square reveals boat location

### ISSUE THREAD

**Issue by jvont** [harry-th/boatleship2#2]
After orange's protected square is no longer protected, it will sometimes reveal a boat once it has moved

**Comment by harry-th** [comment]
The issue was that the mine key of the orangeshotresults object was not deleted when it was sent to the enemy. Mine squares will be sent to your boardstate but not to the opponents, the mine squares sent to the opponent should be replaced with null squares. The null squares were added but the mine squares were not removed, though they would only be revealed on the turn when the freeshot happened due to how the state was being changed.
